"""
This type stub file was generated by pyright.
"""

import pathlib
from collections.abc import Iterable
from mitmproxy import flow

web_dir = ...
def save_static(path: pathlib.Path) -> None:
    """
    Save the files for the static web view.
    """
    ...

def save_filter_help(path: pathlib.Path) -> None:
    ...

def save_settings(path: pathlib.Path) -> None:
    ...

def save_flows(path: pathlib.Path, flows: Iterable[flow.Flow]) -> None:
    ...

def save_flows_content(path: pathlib.Path, flows: Iterable[flow.Flow]) -> None:
    ...

class StaticViewer:
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def export(self, path: pathlib.Path, flows: Iterable[flow.Flow]) -> None:
        ...
    


