"""
This type stub file was generated by pyright.
"""

class WebAddon:
    def load(self, loader): # -> None:
        ...
    
    def running(self): # -> None:
        ...
    


def open_browser(url: str) -> bool:
    """
    Open a URL in a browser window.
    In contrast to webbrowser.open, we limit the list of suitable browsers.
    This gracefully degrades to a no-op on headless servers, where webbrowser.open
    would otherwise open lynx.

    Returns:
        True, if a browser has been opened
        False, if no suitable browser has been found.
    """
    ...

