"""
This type stub file was generated by pyright.
"""

import collections

def random_user_agent(): # -> LiteralString:
    ...

class HTTPHeaderDict(collections.UserDict, dict):
    """
    Store and access keys case-insensitively.
    The constructor can take multiple dicts, in which keys in the latter are prioritised.
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __getitem__(self, key):
        ...
    
    def __delitem__(self, key): # -> None:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    


std_headers = ...
def clean_proxies(proxies: dict, headers: HTTPHeaderDict): # -> None:
    ...

def clean_headers(headers: HTTPHeaderDict): # -> None:
    ...

def remove_dot_segments(path): # -> LiteralString:
    ...

def escape_rfc3986(s): # -> str:
    """Escape non-ASCII characters as suggested by RFC 3986"""
    ...

def normalize_url(url):
    """Normalize URL as suggested by RFC 3986"""
    ...

