"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class FloatplaneIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class FloatplaneChannelIE(InfoExtractor):
    _VALID_URL = ...
    _PAGE_SIZE = ...
    _TESTS = ...


