"""
This type stub file was generated by pyright.
"""

from .arkena import ArkenaIE
from .common import InfoExtractor

class LcpPlayIE(ArkenaIE):
    _VALID_URL = ...
    _TESTS = ...


class LcpIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


