"""
This type stub file was generated by pyright.
"""

from .cbs import CBSBaseIE
from .common import InfoExtractor

class ParamountPlusIE(CBSBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class ParamountPlusSeriesIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


