"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class WeiboBaseIE(InfoExtractor):
    ...


class WeiboIE(WeiboBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class WeiboVideoIE(WeiboBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class WeiboUserIE(WeiboBaseIE):
    _VALID_URL = ...
    _TESTS = ...


