"""
This type stub file was generated by pyright.
"""

from . import base

class ViewAuto(base.View):
    name = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['No content'], list[Unknown]] | TViewResult:
        ...
    
    def render_priority(self, data: bytes, **metadata) -> float:
        ...
    


