"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from collections.abc import Iterable, Iterator, Mapping
from typing import ClassVar, Union
from mitmproxy import flow, http

KEY_MAX = ...
TTextType = Union[str, bytes]
TViewLine = list[tuple[str, TTextType]]
TViewResult = tuple[str, Iterator[TViewLine]]
class View(ABC):
    name: ClassVar[str]
    @abstractmethod
    def __call__(self, data: bytes, *, content_type: str | None = ..., flow: flow.Flow | None = ..., http_message: http.Message | None = ..., **unknown_metadata) -> TViewResult:
        """
        Transform raw data into human-readable output.

        Returns a (description, content generator) tuple.
        The content generator yields lists of (style, text) tuples, where each list represents
        a single line. ``text`` is a unfiltered string which may need to be escaped,
        depending on the used output. For example, it may contain terminal control sequences
        or unfiltered HTML.

        Except for `data`, implementations must not rely on any given argument to be present.
        To ensure compatibility with future mitmproxy versions, unknown keyword arguments should be ignored.

        The content generator must not yield tuples of tuples, because urwid cannot process that.
        You have to yield a *list* of tuples per line.
        """
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., flow: flow.Flow | None = ..., http_message: http.Message | None = ..., **unknown_metadata) -> float:
        """
        Return the priority of this view for rendering `data`.
        If no particular view is chosen by the user, the view with the highest priority is selected.

        Except for `data`, implementations must not rely on any given argument to be present.
        To ensure compatibility with future mitmproxy versions, unknown keyword arguments should be ignored.
        """
        ...
    
    def __lt__(self, other) -> bool:
        ...
    


def format_pairs(items: Iterable[tuple[TTextType, TTextType]]) -> Iterator[TViewLine]:
    """
    Helper function that accepts a list of (k,v) pairs into a list of
    [
        ("key", key    )
        ("value", value)
    ]
    where key is padded to a uniform width
    """
    ...

def format_dict(d: Mapping[TTextType, TTextType]) -> Iterator[TViewLine]:
    """
    Helper function that transforms the given dictionary into a list of
    [
        ("key",   key  )
        ("value", value)
    ]
    entries, where key is padded to a uniform width.
    """
    ...

def format_text(text: TTextType) -> Iterator[TViewLine]:
    """
    Helper function that transforms bytes into the view output format.
    """
    ...

