"""
This type stub file was generated by pyright.
"""

from typing import Any
from mitmproxy.contentviews import base

def format_graphql(data): # -> str:
    ...

def format_query_list(data: list[Any]): # -> str:
    ...

def is_graphql_query(data): # -> bool:
    ...

def is_graphql_batch_query(data): # -> bool:
    ...

class ViewGraphQL(base.View):
    name = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['GraphQL'], Iterator[TViewLine]] | None:
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., **metadata) -> float:
        ...
    


