"""
This type stub file was generated by pyright.
"""

from . import base

class ViewHexDump(base.View):
    name = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['Hexdump'], Generator[list[Unknown], Any, None]]:
        ...
    
    def render_priority(self, data: bytes, **metadata) -> float:
        ...
    


class ViewHexStream(base.View):
    name = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['Raw Hex Stream'], Iterator[TViewLine]]:
        ...
    
    def render_priority(self, data: bytes, **metadata) -> float:
        ...
    


