"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator
from functools import lru_cache
from typing import Any
from mitmproxy.contentviews import base

PARSE_ERROR = ...
@lru_cache(1)
def parse_json(s: bytes) -> Any:
    ...

def format_json(data: Any) -> Iterator[base.TViewLine]:
    ...

class ViewJSON(base.View):
    name = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['JSON'], Iterator[TViewLine]] | None:
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., **metadata) -> float:
        ...
    


