"""
This type stub file was generated by pyright.
"""

from mitmproxy.contentviews import base

class MQTTControlPacket:
    Names = ...
    PACKETS_WITH_IDENTIFIER = ...
    def __init__(self, packet) -> None:
        ...
    
    def pprint(self): # -> str:
        ...
    


class ViewMQTT(base.View):
    name = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['MQTT'], Iterator[TViewLine]]:
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., **metadata) -> float:
        ...
    


