"""
This type stub file was generated by pyright.
"""

from typing import Any
from mitmproxy.contentviews import base

PARSE_ERROR = ...
def parse_msgpack(s: bytes) -> Any:
    ...

def format_msgpack(data: Any, output=..., indent_count: int = ...) -> list[base.TViewLine]:
    ...

class ViewMsgPack(base.View):
    name = ...
    __content_types = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['MsgPack'], list[TViewLine]] | None:
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., **metadata) -> float:
        ...
    


