"""
This type stub file was generated by pyright.
"""

from .. import http
from . import base

class ViewMultipart(base.View):
    name = ...
    def __call__(self, data: bytes, content_type: str | None = ..., http_message: http.Message | None = ..., **metadata): # -> tuple[Literal['Multipart form'], Generator[list[tuple[Literal['highlight'], Literal['Form data:\n']]] | TViewLine, Unknown, None]] | None:
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., **metadata) -> float:
        ...
    


