"""
This type stub file was generated by pyright.
"""

from .. import http
from . import base

class ViewQuery(base.View):
    name = ...
    def __call__(self, data: bytes, http_message: http.Message | None = ..., **metadata): # -> tuple[Literal['Query'], Iterator[TViewLine]]:
        ...
    
    def render_priority(self, data: bytes, *, http_message: http.Message | None = ..., **metadata) -> float:
        ...
    


