"""
This type stub file was generated by pyright.
"""

from . import base

class ViewURLEncoded(base.View):
    name = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['URLEncoded form'], Iterator[TViewLine]] | None:
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., **metadata) -> float:
        ...
    


