"""
This type stub file was generated by pyright.
"""

from . import base

class ViewWBXML(base.View):
    name = ...
    __content_types = ...
    def __call__(self, data, **metadata): # -> tuple[Literal['WBXML'], Iterator[TViewLine]] | None:
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., **metadata) -> float:
        ...
    


