from cx_Freeze import setup, Executable  # not my fault
from cx_Freeze.command.bdist_msi import bdist_msi, suppress_known_deprecation
from constants import version
import re
import typing

with suppress_known_deprecation():
    from msilib import add_data, Binary


def _is_valid_guid(code: typing.Any) -> bool:
    pattern = re.compile(
        r"^\{[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}\}$", re.IGNORECASE
    )
    return isinstance(code, str) and pattern.match(code) is not None


def monkeypatched_add_properties(self: bdist_msi):
    metadata = self.distribution.metadata
    props = [
        ("DistVersion", metadata.get_version()),
        ("ErrorDialog", "ErrorDlg"),
        ("Progress1", "Install"),
        ("Progress2", "installs"),
        ("MaintenanceForm_Action", "Repair"),
        ("ALLUSERS", "2"),
    ]

    if not self.all_users: # bool
        props.append(("MSIINSTALLPERUSER", "1"))
    email = metadata.author_email or metadata.maintainer_email
    if email:
        props.append(("ARPCONTACT", email))
    if metadata.url:
        props.append(("ARPURLINFOABOUT", metadata.url))
    if self.upgrade_code is not None: # str | none
        if not _is_valid_guid(self.upgrade_code):
            msg = "upgrade-code must be in valid GUID format"
            raise ValueError(msg)
        props.append(("UpgradeCode", self.upgrade_code.upper()))
    if self.install_icon: # str | none
        props.append(("ARPPRODUCTICON", "InstallIcon"))
    assert self.db is not None # _Database | None
    add_data(self.db, "Property", props)  # not my fault
    if self.install_icon:
        add_data(
            self.db,  # not my fault
            "Icon",
            [("InstallIcon", Binary(self.install_icon))],
        )


bdist_msi.add_ui = lambda self: None
bdist_msi.add_properties = monkeypatched_add_properties

setup(
    name="Boogie",
    version=str(version),
    description="Boogie",
    options={
        "build_exe": {
            "includes": ["mitmproxy_windows"],
            "packages": "passlib",
            "include_msvcr": True,
        },
        "bdist_msi": {
            "data": {
                "Dialog": [
                    (
                        "FatalError",
                        50,
                        50,
                        370,
                        270,
                        7,
                        "[ProductName] Setup",
                        "Finish",
                        "Finish",
                        "Finish",
                    ),
                    (
                        "UserExit",
                        50,
                        50,
                        370,
                        270,
                        7,
                        "[ProductName] Setup",
                        "Finish",
                        "Finish",
                        "Finish",
                    ),
                    (
                        "ExitDialog",
                        50,
                        50,
                        370,
                        270,
                        7,
                        "[ProductName] Setup",
                        "Finish",
                        "Finish",
                        "Finish",
                    ),
                    (
                        "ProgressDlg",
                        50,
                        50,
                        370,
                        270,
                        5,
                        "[ProductName] Setup",
                        "Cancel",
                        "Cancel",
                        "Cancel",
                    ),
                    (
                        "CancelDlg",
                        50,
                        50,
                        260,
                        85,
                        7,
                        "[ProductName] Setup",
                        "No",
                        "No",
                        "No",
                    ),
                    (
                        "ErrorDlg",
                        50,
                        50,
                        270,
                        105,
                        65543,
                        "[ProductName] Setup",
                        "ErrorText",
                        None,
                        None,
                    ),
                    (
                        "FilesInUse",
                        50,
                        50,
                        370,
                        270,
                        23,
                        "[ProductName] Setup",
                        "Retry",
                        "Retry",
                        "Retry",
                    ),
                    (
                        "WelcomeDlg",
                        50,
                        50,
                        370,
                        270,
                        7,
                        "[ProductName] Setup",
                        "Next",
                        "Next",
                        "Cancel",
                    ),
                ],
                "Control": [
                    (
                        "FatalError",
                        "Description",
                        "Text",
                        135,
                        70,
                        220,
                        80,
                        196611,
                        None,
                        "[ProductName] Setup Wizard ended prematurely because of an error. Your system has not been modified. To install this program at a later time, run Setup Wizard again. Click the Finish button to exit the Setup Wizard.",
                        None,
                        None,
                    ),
                    (
                        "FatalError",
                        "Title",
                        "Text",
                        135,
                        20,
                        220,
                        60,
                        196611,
                        None,
                        "{\\WixUI_Font_Bigger}[ProductName] Setup Wizard ended prematurely",
                        None,
                        None,
                    ),
                    (
                        "FatalError",
                        "Cancel",
                        "PushButton",
                        304,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "Cancel",
                        "Bitmap",
                        None,
                    ),
                    (
                        "FatalError",
                        "Bitmap",
                        "Bitmap",
                        0,
                        0,
                        370,
                        234,
                        1,
                        None,
                        "WixUI_Bmp_Dialog",
                        "Back",
                        None,
                    ),
                    (
                        "FatalError",
                        "Back",
                        "PushButton",
                        180,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "&Back",
                        "Finish",
                        None,
                    ),
                    (
                        "FatalError",
                        "BottomLine",
                        "Line",
                        0,
                        234,
                        370,
                        0,
                        1,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "FatalError",
                        "Finish",
                        "PushButton",
                        236,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "&Finish",
                        "Cancel",
                        None,
                    ),
                    (
                        "UserExit",
                        "Description",
                        "Text",
                        135,
                        80,
                        220,
                        80,
                        196611,
                        None,
                        "[ProductName] setup was interrupted. Your system has not been modified. To install this program at a later time, please run the installation again. Click the Finish button to exit the Setup Wizard.",
                        None,
                        None,
                    ),
                    (
                        "UserExit",
                        "Title",
                        "Text",
                        135,
                        20,
                        220,
                        60,
                        196611,
                        None,
                        "{\\WixUI_Font_Bigger}[ProductName] Setup Wizard was interrupted",
                        None,
                        None,
                    ),
                    (
                        "UserExit",
                        "Cancel",
                        "PushButton",
                        304,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "Cancel",
                        "Bitmap",
                        None,
                    ),
                    (
                        "UserExit",
                        "Bitmap",
                        "Bitmap",
                        0,
                        0,
                        370,
                        234,
                        1,
                        None,
                        "WixUI_Bmp_Dialog",
                        "Back",
                        None,
                    ),
                    (
                        "UserExit",
                        "Back",
                        "PushButton",
                        180,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "&Back",
                        "Finish",
                        None,
                    ),
                    (
                        "UserExit",
                        "BottomLine",
                        "Line",
                        0,
                        234,
                        370,
                        0,
                        1,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "UserExit",
                        "Finish",
                        "PushButton",
                        236,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "&Finish",
                        "Cancel",
                        None,
                    ),
                    (
                        "ExitDialog",
                        "Description",
                        "Text",
                        135,
                        70,
                        220,
                        40,
                        196611,
                        None,
                        "Click the Finish button to exit the Setup Wizard.",
                        None,
                        None,
                    ),
                    (
                        "ExitDialog",
                        "Title",
                        "Text",
                        135,
                        20,
                        220,
                        60,
                        196611,
                        None,
                        "{\\WixUI_Font_Bigger}Completed the [ProductName] Setup Wizard",
                        None,
                        None,
                    ),
                    (
                        "ExitDialog",
                        "Cancel",
                        "PushButton",
                        304,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "Cancel",
                        "Bitmap",
                        None,
                    ),
                    (
                        "ExitDialog",
                        "Bitmap",
                        "Bitmap",
                        0,
                        0,
                        370,
                        234,
                        1,
                        None,
                        "WixUI_Bmp_Dialog",
                        "Back",
                        None,
                    ),
                    (
                        "ExitDialog",
                        "Back",
                        "PushButton",
                        180,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "&Back",
                        "OptionalCheckBox",
                        None,
                    ),
                    (
                        "ExitDialog",
                        "BottomLine",
                        "Line",
                        0,
                        234,
                        370,
                        0,
                        1,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "ExitDialog",
                        "Finish",
                        "PushButton",
                        236,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "&Finish",
                        "Cancel",
                        None,
                    ),
                    (
                        "ExitDialog",
                        "OptionalCheckBox",
                        "CheckBox",
                        135,
                        190,
                        220,
                        40,
                        2,
                        "WIXUI_EXITDIALOGOPTIONALCHECKBOX",
                        "[WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT]",
                        "Finish",
                        None,
                    ),
                    (
                        "ExitDialog",
                        "OptionalText",
                        "Text",
                        135,
                        110,
                        220,
                        80,
                        196610,
                        None,
                        "[WIXUI_EXITDIALOGOPTIONALTEXT]",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "Cancel",
                        "PushButton",
                        304,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "Cancel",
                        "BannerBitmap",
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "BannerBitmap",
                        "Bitmap",
                        0,
                        0,
                        370,
                        44,
                        1,
                        None,
                        "WixUI_Bmp_Banner",
                        "Back",
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "Back",
                        "PushButton",
                        180,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "&Back",
                        "Next",
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "Next",
                        "PushButton",
                        236,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "&Next",
                        "Cancel",
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "BannerLine",
                        "Line",
                        0,
                        44,
                        370,
                        0,
                        1,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "BottomLine",
                        "Line",
                        0,
                        234,
                        370,
                        0,
                        1,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TextInstalling",
                        "Text",
                        20,
                        65,
                        330,
                        35,
                        131074,
                        None,
                        "Please wait while the Setup Wizard installs [ProductName].",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TitleInstalling",
                        "Text",
                        20,
                        15,
                        330,
                        15,
                        196610,
                        None,
                        "{\\WixUI_Font_Title}Installing [ProductName]",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TextChanging",
                        "Text",
                        20,
                        65,
                        330,
                        35,
                        131074,
                        None,
                        "Please wait while the Setup Wizard changes [ProductName].",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TitleChanging",
                        "Text",
                        20,
                        15,
                        330,
                        15,
                        196610,
                        None,
                        "{\\WixUI_Font_Title}Changing [ProductName]",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TextRepairing",
                        "Text",
                        20,
                        65,
                        330,
                        35,
                        131074,
                        None,
                        "Please wait while the Setup Wizard repairs [ProductName].",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TitleRepairing",
                        "Text",
                        20,
                        15,
                        330,
                        15,
                        196610,
                        None,
                        "{\\WixUI_Font_Title}Repairing [ProductName]",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TextRemoving",
                        "Text",
                        20,
                        65,
                        330,
                        35,
                        131074,
                        None,
                        "Please wait while the Setup Wizard removes [ProductName].",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TitleRemoving",
                        "Text",
                        20,
                        15,
                        330,
                        15,
                        196610,
                        None,
                        "{\\WixUI_Font_Title}Removing [ProductName]",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TextUpdating",
                        "Text",
                        20,
                        65,
                        330,
                        35,
                        131074,
                        None,
                        "Please wait while the Setup Wizard updates [ProductName].",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "TitleUpdating",
                        "Text",
                        20,
                        15,
                        330,
                        15,
                        196610,
                        None,
                        "{\\WixUI_Font_Title}Updating [ProductName]",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "ActionText",
                        "Text",
                        70,
                        100,
                        285,
                        10,
                        3,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "ProgressBar",
                        "ProgressBar",
                        20,
                        115,
                        330,
                        10,
                        65537,
                        None,
                        "Progress done",
                        None,
                        None,
                    ),
                    (
                        "ProgressDlg",
                        "StatusLabel",
                        "Text",
                        20,
                        100,
                        50,
                        10,
                        3,
                        None,
                        "Status:",
                        None,
                        None,
                    ),
                    (
                        "CancelDlg",
                        "Text",
                        "Text",
                        48,
                        15,
                        194,
                        30,
                        131075,
                        None,
                        "Are you sure you want to cancel [ProductName] installation?",
                        None,
                        None,
                    ),
                    (
                        "CancelDlg",
                        "Icon",
                        "Icon",
                        15,
                        15,
                        24,
                        24,
                        5242881,
                        None,
                        "WixUI_Ico_Info",
                        None,
                        "Information icon|",
                    ),
                    (
                        "CancelDlg",
                        "No",
                        "PushButton",
                        132,
                        57,
                        56,
                        17,
                        3,
                        None,
                        "&No",
                        "Yes",
                        None,
                    ),
                    (
                        "CancelDlg",
                        "Yes",
                        "PushButton",
                        72,
                        57,
                        56,
                        17,
                        3,
                        None,
                        "&Yes",
                        "No",
                        None,
                    ),
                    (
                        "ErrorDlg",
                        "N",
                        "PushButton",
                        100,
                        80,
                        56,
                        17,
                        3,
                        None,
                        "&No",
                        None,
                        None,
                    ),
                    (
                        "ErrorDlg",
                        "Y",
                        "PushButton",
                        100,
                        80,
                        56,
                        17,
                        3,
                        None,
                        "&Yes",
                        None,
                        None,
                    ),
                    (
                        "ErrorDlg",
                        "ErrorText",
                        "Text",
                        48,
                        15,
                        205,
                        60,
                        131075,
                        None,
                        "Information text",
                        None,
                        None,
                    ),
                    (
                        "ErrorDlg",
                        "A",
                        "PushButton",
                        100,
                        80,
                        56,
                        17,
                        3,
                        None,
                        "Cancel",
                        None,
                        None,
                    ),
                    (
                        "ErrorDlg",
                        "C",
                        "PushButton",
                        100,
                        80,
                        56,
                        17,
                        3,
                        None,
                        "Cancel",
                        None,
                        None,
                    ),
                    (
                        "ErrorDlg",
                        "ErrorIcon",
                        "Icon",
                        15,
                        15,
                        24,
                        24,
                        5242881,
                        None,
                        "WixUI_Ico_Info",
                        None,
                        "Information icon|",
                    ),
                    (
                        "ErrorDlg",
                        "I",
                        "PushButton",
                        100,
                        80,
                        56,
                        17,
                        3,
                        None,
                        "&Ignore",
                        None,
                        None,
                    ),
                    (
                        "ErrorDlg",
                        "O",
                        "PushButton",
                        100,
                        80,
                        56,
                        17,
                        3,
                        None,
                        "OK",
                        None,
                        None,
                    ),
                    (
                        "ErrorDlg",
                        "R",
                        "PushButton",
                        100,
                        80,
                        56,
                        17,
                        3,
                        None,
                        "&Retry",
                        None,
                        None,
                    ),
                    (
                        "FilesInUse",
                        "Description",
                        "Text",
                        20,
                        23,
                        280,
                        20,
                        196611,
                        None,
                        "Some files that need to be updated are currently in use.",
                        None,
                        None,
                    ),
                    (
                        "FilesInUse",
                        "Text",
                        "Text",
                        20,
                        55,
                        330,
                        30,
                        3,
                        None,
                        "The following applications are using files that need to be updated by this setup. Close these applications and then click &Retry to continue setup or Exit to exit it.",
                        None,
                        None,
                    ),
                    (
                        "FilesInUse",
                        "Title",
                        "Text",
                        15,
                        6,
                        200,
                        15,
                        196611,
                        None,
                        "{\\WixUI_Font_Title}Files in Use",
                        None,
                        None,
                    ),
                    (
                        "FilesInUse",
                        "BannerBitmap",
                        "Bitmap",
                        0,
                        0,
                        370,
                        44,
                        1,
                        None,
                        "WixUI_Bmp_Banner",
                        "Retry",
                        None,
                    ),
                    (
                        "FilesInUse",
                        "BannerLine",
                        "Line",
                        0,
                        44,
                        370,
                        0,
                        1,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "FilesInUse",
                        "BottomLine",
                        "Line",
                        0,
                        234,
                        370,
                        0,
                        1,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "FilesInUse",
                        "Retry",
                        "PushButton",
                        304,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "&Retry",
                        "Ignore",
                        None,
                    ),
                    (
                        "FilesInUse",
                        "Ignore",
                        "PushButton",
                        235,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "&Ignore",
                        "Exit",
                        None,
                    ),
                    (
                        "FilesInUse",
                        "Exit",
                        "PushButton",
                        166,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "E&xit",
                        "BannerBitmap",
                        None,
                    ),
                    (
                        "FilesInUse",
                        "List",
                        "ListBox",
                        20,
                        87,
                        330,
                        130,
                        7,
                        "FileInUseProcess",
                        None,
                        None,
                        None,
                    ),
                    (
                        "WelcomeDlg",
                        "Description",
                        "Text",
                        135,
                        80,
                        220,
                        60,
                        196611,
                        None,
                        "The Setup Wizard will install [ProductName] on your computer. Click Next to continue or Cancel to exit the Setup Wizard.",
                        None,
                        None,
                    ),
                    (
                        "WelcomeDlg",
                        "Title",
                        "Text",
                        135,
                        20,
                        220,
                        60,
                        196611,
                        None,
                        "{\\WixUI_Font_Bigger}Welcome to the [ProductName] Setup Wizard",
                        None,
                        None,
                    ),
                    (
                        "WelcomeDlg",
                        "Cancel",
                        "PushButton",
                        304,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "Cancel",
                        "Bitmap",
                        None,
                    ),
                    (
                        "WelcomeDlg",
                        "Bitmap",
                        "Bitmap",
                        0,
                        0,
                        370,
                        234,
                        1,
                        None,
                        "WixUI_Bmp_Dialog",
                        "Back",
                        None,
                    ),
                    (
                        "WelcomeDlg",
                        "Back",
                        "PushButton",
                        180,
                        243,
                        56,
                        17,
                        1,
                        None,
                        "&Back",
                        "Next",
                        None,
                    ),
                    (
                        "WelcomeDlg",
                        "Next",
                        "PushButton",
                        236,
                        243,
                        56,
                        17,
                        3,
                        None,
                        "&Next",
                        "Cancel",
                        None,
                    ),
                    (
                        "WelcomeDlg",
                        "BottomLine",
                        "Line",
                        0,
                        234,
                        370,
                        0,
                        1,
                        None,
                        None,
                        None,
                        None,
                    ),
                    (
                        "WelcomeDlg",
                        "PatchDescription",
                        "Text",
                        135,
                        80,
                        220,
                        60,
                        196611,
                        None,
                        "The Setup Wizard will update [ProductName] on your computer. Click Next to continue or Cancel to exit the Setup Wizard.",
                        None,
                        None,
                    ),
                ],
                "ControlEvent": [
                    ("FatalError", "Finish", "EndDialog", "Exit", "1", 1),
                    ("UserExit", "Finish", "EndDialog", "Exit", "1", 1),
                    ("ExitDialog", "Finish", "EndDialog", "Return", "1", 999),
                    ("ProgressDlg", "Cancel", "SpawnDialog", "CancelDlg", "1", 1),
                    ("CancelDlg", "No", "EndDialog", "Return", "1", 1),
                    ("CancelDlg", "Yes", "EndDialog", "Exit", "1", 1),
                    ("ErrorDlg", "N", "EndDialog", "ErrorNo", "1", 1),
                    ("ErrorDlg", "Y", "EndDialog", "ErrorYes", "1", 1),
                    ("ErrorDlg", "A", "EndDialog", "ErrorAbort", "1", 1),
                    ("ErrorDlg", "C", "EndDialog", "ErrorCancel", "1", 1),
                    ("ErrorDlg", "I", "EndDialog", "ErrorIgnore", "1", 1),
                    ("ErrorDlg", "O", "EndDialog", "ErrorOk", "1", 1),
                    ("ErrorDlg", "R", "EndDialog", "ErrorRetry", "1", 1),
                    ("FilesInUse", "Retry", "EndDialog", "Retry", "1", 1),
                    ("FilesInUse", "Ignore", "EndDialog", "Ignore", "1", 1),
                    ("FilesInUse", "Exit", "EndDialog", "Exit", "1", 1),
                    ("WelcomeDlg", "Cancel", "SpawnDialog", "CancelDlg", "1", 1),
                    ("WelcomeDlg", "Next", "NewDialog", "ProgressDlg", "1", 1),
                ],
                "EventMapping": [
                    ("ProgressDlg", "ActionText", "ActionText", "Text"),
                    ("ProgressDlg", "ProgressBar", "SetProgress", "Progress"),
                ],
                "ControlCondition": [
                    (
                        "ExitDialog",
                        "OptionalCheckBox",
                        "Show",
                        "WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT AND NOT Installed",
                    ),
                    (
                        "ExitDialog",
                        "OptionalText",
                        "Show",
                        "WIXUI_EXITDIALOGOPTIONALTEXT AND NOT Installed",
                    ),
                    (
                        "ProgressDlg",
                        "TextInstalling",
                        "Show",
                        "NOT Installed OR (Installed AND (RESUME OR Preselected) AND NOT PATCH)",
                    ),
                    (
                        "ProgressDlg",
                        "TitleInstalling",
                        "Show",
                        "NOT Installed OR (Installed AND (RESUME OR Preselected) AND NOT PATCH)",
                    ),
                    (
                        "ProgressDlg",
                        "TextChanging",
                        "Show",
                        'WixUI_InstallMode = "Change"',
                    ),
                    (
                        "ProgressDlg",
                        "TitleChanging",
                        "Show",
                        'WixUI_InstallMode = "Change"',
                    ),
                    (
                        "ProgressDlg",
                        "TextRepairing",
                        "Show",
                        'WixUI_InstallMode = "Repair"',
                    ),
                    (
                        "ProgressDlg",
                        "TitleRepairing",
                        "Show",
                        'WixUI_InstallMode = "Repair"',
                    ),
                    (
                        "ProgressDlg",
                        "TextRemoving",
                        "Show",
                        'WixUI_InstallMode = "Remove"',
                    ),
                    (
                        "ProgressDlg",
                        "TitleRemoving",
                        "Show",
                        'WixUI_InstallMode = "Remove"',
                    ),
                    (
                        "ProgressDlg",
                        "TextUpdating",
                        "Show",
                        'WixUI_InstallMode = "Update"',
                    ),
                    (
                        "ProgressDlg",
                        "TitleUpdating",
                        "Show",
                        'WixUI_InstallMode = "Update"',
                    ),
                    ("WelcomeDlg", "Description", "Show", "NOT Installed OR NOT PATCH"),
                    ("WelcomeDlg", "Description", "Hide", "Installed AND PATCH"),
                    ("WelcomeDlg", "PatchDescription", "Show", "Installed AND PATCH"),
                    (
                        "WelcomeDlg",
                        "PatchDescription",
                        "Hide",
                        "NOT Installed OR NOT PATCH",
                    ),
                ],
                "RadioButton": [
                    (
                        "WixAppFolder",
                        1,
                        "WixPerUserFolder",
                        0,
                        0,
                        295,
                        16,
                        "{\\WixUI_Font_Emphasized}Install &just for you ([LogonUser])",
                        None,
                    ),
                    (
                        "WixAppFolder",
                        2,
                        "WixPerMachineFolder",
                        0,
                        60,
                        295,
                        16,
                        "{\\WixUI_Font_Emphasized}Install for all users of this &machine",
                        None,
                    ),
                ],
                "TextStyle": [
                    ("WixUI_Font_Normal", "Tahoma", 8, None, None),
                    ("WixUI_Font_Bigger", "Tahoma", 9, None, 1),
                    ("WixUI_Font_Title", "Tahoma", 9, None, 1),
                ],
                "InstallUISequence": [
                    ("WelcomeDlg", "NOT Installed OR PATCH", 1298),
                ],
                "Binary": [
                    (
                        "WixUI_Bmp_Banner",
                        "images/WixUI_Banner.bmp",
                    ),
                    (
                        "WixUI_Bmp_Dialog",
                        "images/WixUI_Dialog.bmp",
                    ),
                    (
                        "WixUI_Ico_Exclam",
                        "images/WixUI_Exclam.ico",
                    ),
                    (
                        "WixUI_Ico_Info",
                        "images/WixUI_Info.ico",
                    ),
                    (
                        "WixUI_Bmp_New",
                        "images/WixUI_New.bmp",
                    ),
                    (
                        "WixUI_Bmp_Up",
                        "images/WixUI_Up.bmp",
                    ),
                ],
                "Property": [("DefaultUIFont", "WixUI_Font_Normal")],
                "Registry": [
                    (
                        "url-protocol",
                        0,
                        "boogie",
                        "URL Protocol",
                        "",
                        "_cx_executable0__Executable_script_main.py_",
                    ),
                    (
                        "default",
                        0,
                        r"boogie\shell\open\command",
                        None,
                        '"[TARGETDIR]main.exe" "%1"',
                        "_cx_executable0__Executable_script_main.py_",
                    ),
                ],
            },
            "install_icon": "icon.ico",
            "upgrade_code": "{B0061321-28C7-CA76-8337-371013377181}",
        },
    },
    executables=[
        Executable(
            "main.py",
            shortcut_dir="ProgramMenuFolder",
            shortcut_name="Boogie",
            icon="icon",
            base="gui",
        )
    ],
)
