"""
This type stub file was generated by pyright.
"""

from functools import cache
from typing import Literal

"""
Server specs are used to describe an upstream proxy or server.
"""
ServerSpec = tuple[Literal["http", "https", "http3", "tls", "dtls", "tcp", "udp", "dns", "quic"], tuple[str, int],]
server_spec_re = ...
@cache
def parse(server_spec: str, default_scheme: str) -> ServerSpec:
    """
    Parses a server mode specification, e.g.:

     - http://example.com/
     - example.org
     - example.com:443

    *Raises:*
     - ValueError, if the server specification is invalid.
    """
    ...

