"""
This type stub file was generated by pyright.
"""

class Data:
    def __init__(self, name) -> None:
        ...
    
    def push(self, subpath): # -> Data:
        """
        Change the data object to a path relative to the module.
        """
        ...
    
    def path(self, path): # -> str:
        """
        Returns a path to the package data housed at 'path' under this
        module.Path can be a path to a file, or to a directory.

        This function will raise ValueError if the path does not exist.
        """
        ...
    


pkg_data = ...
