"""
This type stub file was generated by pyright.
"""

import functools

SIZE_UNITS = ...
def pretty_size(size: int) -> str:
    """Convert a number of bytes into a human-readable string.

    len(return value) <= 5 always holds true.
    """
    ...

@functools.lru_cache
def parse_size(s: str | None) -> int | None:
    """
    Parse a size with an optional k/m/... suffix.
    Invalid values raise a ValueError. For added convenience, passing `None` returns `None`.
    """
    ...

def pretty_duration(secs: float | None) -> str:
    ...

def format_timestamp(s): # -> str:
    ...

def format_timestamp_with_milli(s): # -> str:
    ...

@functools.lru_cache
def format_address(address: tuple | None) -> str:
    """
    This function accepts IPv4/IPv6 tuples and
    returns the formatted address string with port number
    """
    ...

