"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Iterator
from typing import TypeVar

T = TypeVar("T")
def window(iterator: Iterable[T], behind: int = ..., ahead: int = ...) -> Iterator[tuple[T | None, ...]]:
    """
    Sliding window for an iterator.

    Example:
        >>> for prev, i, nxt in window(range(10), 1, 1):
        >>>     print(prev, i, nxt)

        None 0 1
        0 1 2
        1 2 3
        2 3 None
    """
    ...

