"""
This type stub file was generated by pyright.
"""

from mitmproxy import flowfilter

def parse_spec(option: str) -> tuple[flowfilter.TFilter, str, str]:
    """
    Parse strings in the following format:

        [/flow-filter]/subject/replacement

    """
    ...

