"""
This type stub file was generated by pyright.
"""

import typing

Type = typing.Union[typing.Any]
def check_option_type(name: str, value: typing.Any, typeinfo: Type) -> None:
    """
    Check if the provided value is an instance of typeinfo and raises a
    TypeError otherwise. This function supports only those types required for
    options.
    """
    ...

def typespec_to_str(typespec: typing.Any) -> str:
    ...

