"""
This type stub file was generated by pyright.
"""

import mitmproxy.proxy.layer
from typing import TYPE_CHECKING
from mitmproxy import connection
from mitmproxy.options import Options

if TYPE_CHECKING:
    ...
class Context:
    """
    The context object provided to each protocol layer in the proxy core.
    """
    client: connection.Client
    server: connection.Server
    options: Options
    layers: list[mitmproxy.proxy.layer.Layer]
    def __init__(self, client: connection.Client, options: Options) -> None:
        ...
    
    def fork(self) -> Context:
        ...
    
    def __repr__(self): # -> str:
        ...
    


