"""
This type stub file was generated by pyright.
"""

"""
Utility decorators that help build state machines
"""
def expect(*event_types): # -> (f: Unknown) -> (_Wrapped[..., Unknown, (self: Unknown, event: Event), Unknown] | Unknown):
    """
    Only allow the given event type.
    If another event is passed, an AssertionError is raised.
    """
    ...

class ReceiveBuffer:
    """
    A data structure to collect stream contents efficiently in O(n).
    """
    _chunks: list[bytes]
    _len: int
    def __init__(self) -> None:
        ...
    
    def __iadd__(self, other: bytes): # -> Self@ReceiveBuffer:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __bytes__(self): # -> bytes:
        ...
    
    def __bool__(self): # -> bool:
        ...
    
    def clear(self): # -> None:
        ...
    


