"""
This type stub file was generated by pyright.
"""

import kaitaistruct
from kaitaistruct import KaitaiStruct
from enum import Enum

if getattr(kaitaistruct, 'API_VERSION', (0, 9)) < (0, 9):
    ...
class Gif(KaitaiStruct):
    """GIF (Graphics Interchange Format) is an image file format, developed
    in 1987. It became popular in 1990s as one of the main image formats
    used in World Wide Web.
    
    GIF format allows encoding of palette-based images up to 256 colors
    (each of the colors can be chosen from a 24-bit RGB
    colorspace). Image data stream uses LZW (Lempel-Ziv-Welch) lossless
    compression.
    
    Over the years, several version of the format were published and
    several extensions to it were made, namely, a popular Netscape
    extension that allows to store several images in one file, switching
    between them, which produces crude form of animation.
    
    Structurally, format consists of several mandatory headers and then
    a stream of blocks follows. Blocks can carry additional
    metainformation or image data.
    """
    class BlockType(Enum):
        extension = ...
        local_image_descriptor = ...
        end_of_file = ...
    
    
    class ExtensionLabel(Enum):
        graphic_control = ...
        comment = ...
        application = ...
    
    
    def __init__(self, _io, _parent=..., _root=...) -> None:
        ...
    
    class ImageData(KaitaiStruct):
        """
        .. seealso::
           - section 22 - https://www.w3.org/Graphics/GIF/spec-gif89a.txt
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class ColorTableEntry(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class LogicalScreenDescriptorStruct(KaitaiStruct):
        """
        .. seealso::
           - section 18 - https://www.w3.org/Graphics/GIF/spec-gif89a.txt
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
        @property
        def has_color_table(self): # -> Any | None:
            ...
        
        @property
        def color_table_size(self): # -> Any | None:
            ...
        
    
    
    class LocalImageDescriptor(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
        @property
        def has_color_table(self): # -> Any | None:
            ...
        
        @property
        def has_interlace(self): # -> Any | None:
            ...
        
        @property
        def has_sorted_color_table(self): # -> Any | None:
            ...
        
        @property
        def color_table_size(self): # -> Any | None:
            ...
        
    
    
    class Block(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class ColorTable(KaitaiStruct):
        """
        .. seealso::
           - section 19 - https://www.w3.org/Graphics/GIF/spec-gif89a.txt
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Header(KaitaiStruct):
        """
        .. seealso::
           - section 17 - https://www.w3.org/Graphics/GIF/spec-gif89a.txt
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class ExtGraphicControl(KaitaiStruct):
        """
        .. seealso::
           - section 23 - https://www.w3.org/Graphics/GIF/spec-gif89a.txt
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
        @property
        def transparent_color_flag(self): # -> Any | None:
            ...
        
        @property
        def user_input_flag(self): # -> Any | None:
            ...
        
    
    
    class Subblock(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class ApplicationId(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class ExtApplication(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Subblocks(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Extension(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    


