"""
This type stub file was generated by pyright.
"""

import kaitaistruct
from kaitaistruct import KaitaiStruct
from enum import Enum

if getattr(kaitaistruct, 'API_VERSION', (0, 9)) < (0, 9):
    ...
class GoogleProtobuf(KaitaiStruct):
    """Google Protocol Buffers (AKA protobuf) is a popular data
    serialization scheme used for communication protocols, data storage,
    etc. There are implementations are available for almost every
    popular language. The focus points of this scheme are brevity (data
    is encoded in a very size-efficient manner) and extensibility (one
    can add keys to the structure, while keeping it readable in previous
    version of software).
    
    Protobuf uses semi-self-describing encoding scheme for its
    messages. It means that it is possible to parse overall structure of
    the message (skipping over fields one can't understand), but to
    fully understand the message, one needs a protocol definition file
    (`.proto`). To be specific:
    
    * "Keys" in key-value pairs provided in the message are identified
      only with an integer "field tag". `.proto` file provides info on
      which symbolic field names these field tags map to.
    * "Keys" also provide something called "wire type". It's not a data
      type in its common sense (i.e. you can't, for example, distinguish
      `sint32` vs `uint32` vs some enum, or `string` from `bytes`), but
      it's enough information to determine how many bytes to
      parse. Interpretation of the value should be done according to the
      type specified in `.proto` file.
    * There's no direct information on which fields are optional /
      required, which fields may be repeated or constitute a map, what
      restrictions are placed on fields usage in a single message, what
      are the fields' default values, etc, etc.
    
    .. seealso::
       Source - https://developers.google.com/protocol-buffers/docs/encoding
    """
    def __init__(self, _io, _parent=..., _root=...) -> None:
        ...
    
    class Pair(KaitaiStruct):
        """Key-value pair."""
        class WireTypes(Enum):
            varint = ...
            bit_64 = ...
            len_delimited = ...
            group_start = ...
            group_end = ...
            bit_32 = ...
        
        
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
        @property
        def wire_type(self): # -> Any | None:
            """"Wire type" is a part of the "key" that carries enough
            information to parse value from the wire, i.e. read correct
            amount of bytes, but there's not enough informaton to
            interprete in unambiguously. For example, one can't clearly
            distinguish 64-bit fixed-sized integers from 64-bit floats,
            signed zigzag-encoded varints from regular unsigned varints,
            arbitrary bytes from UTF-8 encoded strings, etc.
            """
            ...
        
        @property
        def field_tag(self): # -> Any | None:
            """Identifies a field of protocol. One can look up symbolic
            field name in a `.proto` file by this field tag.
            """
            ...
        
    
    
    class DelimitedBytes(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    


