"""
This type stub file was generated by pyright.
"""

import kaitaistruct
import zlib
from kaitaistruct import KaitaiStruct
from enum import Enum

if getattr(kaitaistruct, 'API_VERSION', (0, 9)) < (0, 9):
    ...
class Png(KaitaiStruct):
    """Test files for APNG can be found at the following locations:
    
      * <https://philip.html5.org/tests/apng/tests.html>
      * <http://littlesvr.ca/apng/>
    """
    class PhysUnit(Enum):
        unknown = ...
        meter = ...
    
    
    class BlendOpValues(Enum):
        source = ...
        over = ...
    
    
    class CompressionMethods(Enum):
        zlib = ...
    
    
    class DisposeOpValues(Enum):
        none = ...
        background = ...
        previous = ...
    
    
    class ColorType(Enum):
        greyscale = ...
        truecolor = ...
        indexed = ...
        greyscale_alpha = ...
        truecolor_alpha = ...
    
    
    def __init__(self, _io, _parent=..., _root=...) -> None:
        ...
    
    class Rgb(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Chunk(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class BkgdIndexed(KaitaiStruct):
        """Background chunk for images with indexed palette."""
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Point(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
        @property
        def x(self): # -> Any | None:
            ...
        
        @property
        def y(self): # -> Any | None:
            ...
        
    
    
    class BkgdGreyscale(KaitaiStruct):
        """Background chunk for greyscale images."""
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class ChrmChunk(KaitaiStruct):
        """
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11cHRM
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class IhdrChunk(KaitaiStruct):
        """
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11IHDR
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class PlteChunk(KaitaiStruct):
        """
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11PLTE
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class SrgbChunk(KaitaiStruct):
        """
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11sRGB
        """
        class Intent(Enum):
            perceptual = ...
            relative_colorimetric = ...
            saturation = ...
            absolute_colorimetric = ...
        
        
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class CompressedTextChunk(KaitaiStruct):
        """Compressed text chunk effectively allows to store key-value
        string pairs in PNG container, compressing "value" part (which
        can be quite lengthy) with zlib compression.
        
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11zTXt
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class FrameDataChunk(KaitaiStruct):
        """
        .. seealso::
           Source - https://wiki.mozilla.org/APNG_Specification#.60fdAT.60:_The_Frame_Data_Chunk
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class BkgdTruecolor(KaitaiStruct):
        """Background chunk for truecolor images."""
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class GamaChunk(KaitaiStruct):
        """
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11gAMA
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
        @property
        def gamma_ratio(self): # -> Any | None:
            ...
        
    
    
    class BkgdChunk(KaitaiStruct):
        """Background chunk stores default background color to display this
        image against. Contents depend on `color_type` of the image.
        
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11bKGD
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class PhysChunk(KaitaiStruct):
        """"Physical size" chunk stores data that allows to translate
        logical pixels into physical units (meters, etc) and vice-versa.
        
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11pHYs
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class FrameControlChunk(KaitaiStruct):
        """
        .. seealso::
           Source - https://wiki.mozilla.org/APNG_Specification#.60fcTL.60:_The_Frame_Control_Chunk
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
        @property
        def delay(self): # -> Any | None:
            """Time to display this frame, in seconds."""
            ...
        
    
    
    class InternationalTextChunk(KaitaiStruct):
        """International text chunk effectively allows to store key-value string pairs in
        PNG container. Both "key" (keyword) and "value" (text) parts are
        given in pre-defined subset of iso8859-1 without control
        characters.
        
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11iTXt
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class TextChunk(KaitaiStruct):
        """Text chunk effectively allows to store key-value string pairs in
        PNG container. Both "key" (keyword) and "value" (text) parts are
        given in pre-defined subset of iso8859-1 without control
        characters.
        
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11tEXt
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class AnimationControlChunk(KaitaiStruct):
        """
        .. seealso::
           Source - https://wiki.mozilla.org/APNG_Specification#.60acTL.60:_The_Animation_Control_Chunk
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class TimeChunk(KaitaiStruct):
        """Time chunk stores time stamp of last modification of this image,
        up to 1 second precision in UTC timezone.
        
        .. seealso::
           Source - https://www.w3.org/TR/PNG/#11tIME
        """
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    


