"""
This type stub file was generated by pyright.
"""

import kaitaistruct
from kaitaistruct import KaitaiStruct

if getattr(kaitaistruct, 'API_VERSION', (0, 9)) < (0, 9):
    ...
class TlsClientHello(KaitaiStruct):
    def __init__(self, _io, _parent=..., _root=...) -> None:
        ...
    
    class ServerName(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Random(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class SessionId(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Sni(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class CipherSuites(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class CompressionMethods(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Alpn(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Extensions(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Version(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Protocol(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    
    class Extension(KaitaiStruct):
        def __init__(self, _io, _parent=..., _root=...) -> None:
            ...
        
    
    


