"""
This type stub file was generated by pyright.
"""

def get_boolean_choice(prompt, default=...): # -> bool:
    ...

def get_int_choice(prompt, default=..., min_choice=..., max_choice=..., return_on_invalid=...): # -> int | None:
    ...

def sdl_prompt(sdl_data, title): # -> list[str]:
    ...

def strtobool(val): # -> Literal[1, 0]:
    """Convert a string representation of truth to true (1) or false (0).

    True values are 'y', 'yes', 't', 'true', 'on', and '1'; false values
    are 'n', 'no', 'f', 'false', 'off', and '0'.  Raises ValueError if
    'val' is anything else.

    Copied from python standard library as distutils.util.strtobool is deprecated.
    """
    ...

