"""
This type stub file was generated by pyright.
"""

def is_pyinstaller(): # -> Any | bool:
    ...

def is_windows_or_pyi(): # -> Any | bool:
    ...

def is_windows_mac_or_pyi(): # -> Any | bool:
    ...

