"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from legendary.models.chunk import Chunk

class SaveGameHelper:
    def __init__(self) -> None:
        ...
    
    def finalize_chunk(self, chunk: Chunk): # -> ChunkInfo:
        ...
    
    def package_savegame(self, input_folder: str, app_name: str = ..., epic_id: str = ..., cloud_folder: str = ..., cloud_folder_mac: str = ..., include_filter: list = ..., exclude_filter: list = ..., manifest_dt: datetime = ...): # -> dict[Unknown, Unknown]:
        """
        :param input_folder: Folder to be packaged into chunks/manifest
        :param app_name: App name for savegame being stored
        :param epic_id: Epic account ID
        :param cloud_folder: Folder the savegame resides in (based on game metadata)
        :param cloud_folder_mac: Folder the macOS savegame resides in (based on game metadata)
        :param include_filter: list of patterns for files to include (excludes all others)
        :param exclude_filter: list of patterns for files to exclude (includes all others)
        :param manifest_dt: datetime for the manifest name (optional)
        :return:
        """
        ...
    
    def get_deletion_list(self, save_folder, include_filter=..., exclude_filter=...): # -> list[Unknown]:
        ...
    


