"""
This type stub file was generated by pyright.
"""

import os
from flask import Flask, render_template
from mitmproxy.options import CONF_BASENAME, CONF_DIR
from mitmproxy.utils.magisk import write_magisk_module

app = ...
@app.route("/")
def index(): # -> str:
    ...

@app.route("/cert/pem")
def pem(): # -> tuple[bytes, dict[str, Unknown]]:
    ...

@app.route("/cert/p12")
def p12(): # -> tuple[bytes, dict[str, Unknown]]:
    ...

@app.route("/cert/cer")
def cer(): # -> tuple[bytes, dict[str, Unknown]]:
    ...

@app.route("/cert/magisk")
def magisk(): # -> tuple[bytes, dict[str, str]]:
    ...

def read_cert(ext, content_type): # -> tuple[bytes, dict[str, Unknown]]:
    ...

