"""
This type stub file was generated by pyright.
"""

from typing import Optional

_LABEL_SIZE = ...
_POINTER_OFFSET = ...
_POINTER_INDICATOR = ...
Cache = dict[int, Optional[tuple[str, int]]]
def cache() -> Cache:
    ...

def unpack_from_with_compression(buffer: bytes, offset: int, cache: Cache) -> tuple[str, int]:
    ...

def unpack_from(buffer: bytes, offset: int) -> tuple[str, int]:
    """Converts RDATA into a domain name without pointer compression from a given offset and also returns the binary size."""
    ...

def unpack(buffer: bytes) -> str:
    """Converts RDATA into a domain name without pointer compression."""
    ...

def pack(name: str) -> bytes:
    """Converts a domain name into RDATA without pointer compression."""
    ...

def record_data_can_have_compression(record_type: int) -> bool:
    ...

def decompress_from_record_data(buffer: bytes, offset: int, end_data: int, cached_names: Cache) -> bytes:
    ...

