"""
This type stub file was generated by pyright.
"""

import enum
from dataclasses import dataclass

class SVCParamKeys(enum.Enum):
    MANDATORY = ...
    ALPN = ...
    NO_DEFAULT_ALPN = ...
    PORT = ...
    IPV4HINT = ...
    ECH = ...
    IPV6HINT = ...


@dataclass
class HTTPSRecord:
    priority: int
    target_name: str
    params: dict[int, bytes]
    def __repr__(self): # -> str:
        ...
    


def unpack(data: bytes) -> HTTPSRecord:
    """
    Unpacks HTTPS RDATA from byte data.

    Raises:
        struct.error if the record is malformed.
    """
    ...

def pack(record: HTTPSRecord) -> bytes:
    """Packs the HTTPS record into its bytes form."""
    ...

