"""
This type stub file was generated by pyright.
"""

from mitmproxy.addons import anticache, anticomp, block, blocklist, browser, clientplayback, command_history, comment, core, cut, disable_h2c, dns_resolver, export, maplocal, mapremote, modifybody, modifyheaders, next_layer, onboarding, proxyauth, proxyserver, save, savehar, script, serverplayback, stickyauth, stickycookie, strip_dns_https_records, tlsconfig, update_alt_svc, upstream_auth

def default_addons(): # -> list[Unknown]:
    ...

