"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple
from mitmproxy import flowfilter, http

class BlockSpec(NamedTuple):
    matches: flowfilter.TFilter
    status_code: int
    ...


def parse_spec(option: str) -> BlockSpec:
    """
    Parses strings in the following format, enforces number of segments:

        /flow-filter/status

    """
    ...

class BlockList:
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def request(self, flow: http.HTTPFlow) -> None:
        ...
    


