"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from mitmproxy import command, flow

class Comment:
    @command.command("flow.comment")
    def comment(self, flow: Sequence[flow.Flow], comment: str) -> None:
        "Add a comment to a flow"
        ...
    


