"""
This type stub file was generated by pyright.
"""

import pathlib
from collections.abc import Sequence
from mitmproxy import command

class CommandHistory:
    VACUUM_SIZE = ...
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    @property
    def history_file(self) -> pathlib.Path:
        ...
    
    def running(self): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def done(self): # -> None:
        ...
    
    @command.command("commands.history.add")
    def add_command(self, command: str) -> None:
        ...
    
    @command.command("commands.history.get")
    def get_history(self) -> Sequence[str]:
        """Get the entire command history."""
        ...
    
    @command.command("commands.history.clear")
    def clear_history(self): # -> None:
        ...
    
    @command.command("commands.history.filter")
    def set_filter(self, prefix: str) -> None:
        ...
    
    @command.command("commands.history.next")
    def get_next(self) -> str:
        ...
    
    @command.command("commands.history.prev")
    def get_prev(self) -> str:
        ...
    


