"""
This type stub file was generated by pyright.
"""

import mitmproxy_rs
from collections.abc import Awaitable, Callable
from functools import cache
from mitmproxy import dns

logger = ...
class DnsResolver:
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    @cache
    def name_servers(self) -> list[str]:
        """
        The Operating System name servers,
        or `[]` if they cannot be determined.
        """
        ...
    
    @cache
    def resolver(self) -> mitmproxy_rs.dns.DnsResolver:
        """
        Our mitmproxy_rs DNS resolver.
        """
        ...
    
    async def dns_request(self, flow: dns.DNSFlow) -> None:
        ...
    
    async def resolve(self, message: dns.Message, resolve_func: Callable[[dns.Question], Awaitable[list[str]]]) -> dns.Message:
        ...
    


