"""
This type stub file was generated by pyright.
"""

import logging
from mitmproxy import log

class ErrorCheck:
    """Monitor startup for error log entries, and terminate immediately if there are some."""
    repeat_errors_on_stderr: bool
    def __init__(self, repeat_errors_on_stderr: bool = ...) -> None:
        ...
    
    def finish(self): # -> None:
        ...
    
    async def shutdown_if_errored(self): # -> None:
        ...
    


class ErrorCheckHandler(log.MitmLogHandler):
    def __init__(self) -> None:
        ...
    
    def emit(self, record: logging.LogRecord) -> None:
        ...
    


