"""
This type stub file was generated by pyright.
"""

import logging
from collections.abc import Callable
from mitmproxy import command, log
from mitmproxy.log import LogEntry

class EventStore:
    def __init__(self, size: int = ...) -> None:
        ...
    
    def done(self): # -> None:
        ...
    
    @property
    def size(self) -> int | None:
        ...
    
    @command.command("eventstore.clear")
    def clear(self) -> None:
        """
        Clear the event log.
        """
        ...
    


class CallbackLogger(log.MitmLogHandler):
    def __init__(self, callback: Callable[[LogEntry], None]) -> None:
        ...
    
    def emit(self, record: logging.LogRecord) -> None:
        ...
    


