"""
This type stub file was generated by pyright.
"""

from mitmproxy import flow, flowfilter

class Intercept:
    filt: flowfilter.TFilter | None = ...
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def should_intercept(self, f: flow.Flow) -> bool:
        ...
    
    def process_flow(self, f: flow.Flow) -> None:
        ...
    
    def request(self, f): # -> None:
        ...
    
    def response(self, f): # -> None:
        ...
    
    def tcp_message(self, f): # -> None:
        ...
    
    def udp_message(self, f): # -> None:
        ...
    
    def dns_request(self, f): # -> None:
        ...
    
    def dns_response(self, f): # -> None:
        ...
    
    def websocket_message(self, f): # -> None:
        ...
    


