"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import NamedTuple
from mitmproxy import flowfilter, http

class MapLocalSpec(NamedTuple):
    matches: flowfilter.TFilter
    regex: str
    local_path: Path
    ...


def parse_map_local_spec(option: str) -> MapLocalSpec:
    ...

def file_candidates(url: str, spec: MapLocalSpec) -> list[Path]:
    """
    Get all potential file candidates given a URL and a mapping spec ordered by preference.
    This function already assumes that the spec regex matches the URL.
    """
    ...

class MapLocal:
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def request(self, flow: http.HTTPFlow) -> None:
        ...
    


