"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple
from mitmproxy import flowfilter, http

class MapRemoteSpec(NamedTuple):
    matches: flowfilter.TFilter
    subject: str
    replacement: str
    ...


def parse_map_remote_spec(option: str) -> MapRemoteSpec:
    ...

class MapRemote:
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def request(self, flow: http.HTTPFlow) -> None:
        ...
    


