"""
This type stub file was generated by pyright.
"""

logger = ...
class ModifyBody:
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def request(self, flow): # -> None:
        ...
    
    def response(self, flow): # -> None:
        ...
    
    def run(self, flow): # -> None:
        ...
    


