"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple
from mitmproxy import flowfilter, http
from mitmproxy.http import Headers

class ModifySpec(NamedTuple):
    matches: flowfilter.TFilter
    subject: bytes
    replacement_str: str
    def read_replacement(self) -> bytes:
        """
        Process the replacement str. This usually just involves converting it to bytes.
        However, if it starts with `@`, we interpret the rest as a file path to read from.

        Raises:
            - IOError if the file cannot be read.
        """
        ...
    


def parse_modify_spec(option: str, subject_is_regex: bool) -> ModifySpec:
    ...

class ModifyHeaders:
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def requestheaders(self, flow): # -> None:
        ...
    
    def responseheaders(self, flow): # -> None:
        ...
    
    def run(self, flow: http.HTTPFlow, hdrs: Headers) -> None:
        ...
    


