"""
This type stub file was generated by pyright.
"""

from mitmproxy.addons import asgiapp

APP_HOST = ...
class Onboarding(asgiapp.WSGIApp):
    name = ...
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    async def request(self, f): # -> None:
        ...
    


