"""
This type stub file was generated by pyright.
"""

from typing import BinaryIO
from mitmproxy import command

logger = ...
class ReadFile:
    """
    An addon that handles reading from file on startup.
    """
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    async def load_flows(self, fo: BinaryIO) -> int:
        ...
    
    async def load_flows_from_path(self, path: str) -> int:
        ...
    
    async def doread(self, rfile: str) -> None:
        ...
    
    def running(self): # -> None:
        ...
    
    @command.command("readfile.reading")
    def reading(self) -> bool:
        ...
    


class ReadFileStdin(ReadFile):
    """Support the special case of "-" for reading from stdin"""
    async def load_flows_from_path(self, path: str) -> int:
        ...
    


