"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from mitmproxy import command, flow, http, types
from mitmproxy.addonmanager import Loader
from mitmproxy.connection import Server
from mitmproxy.coretypes.multidict import _MultiDict

"""Write flow objects to a HAR file"""
logger = ...
class SaveHar:
    def __init__(self) -> None:
        ...
    
    @command.command("save.har")
    def export_har(self, flows: Sequence[flow.Flow], path: types.Path) -> None:
        """Export flows to an HAR (HTTP Archive) file."""
        ...
    
    def make_har(self, flows: Sequence[flow.Flow]) -> dict:
        ...
    
    def load(self, loader: Loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def response(self, flow: http.HTTPFlow) -> None:
        ...
    
    def error(self, flow: http.HTTPFlow) -> None:
        ...
    
    def websocket_end(self, flow: http.HTTPFlow) -> None:
        ...
    
    def done(self): # -> None:
        ...
    
    def flow_entry(self, flow: http.HTTPFlow, servers_seen: set[Server]) -> dict:
        """Creates HAR entry from flow"""
        ...
    
    def format_response_cookies(self, response: http.Response) -> list[dict]:
        """Formats the response's cookie header to list of cookies"""
        ...
    
    def format_multidict(self, obj: _MultiDict[str, str]) -> list[dict]:
        ...
    


