"""
This type stub file was generated by pyright.
"""

class StickyAuth:
    def __init__(self) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def request(self, flow): # -> None:
        ...
    


