"""
This type stub file was generated by pyright.
"""

from mitmproxy import dns

class StripDnsHttpsRecords:
    def load(self, loader): # -> None:
        ...
    
    def dns_response(self, flow: dns.DNSFlow): # -> None:
        ...
    


