"""
This type stub file was generated by pyright.
"""

import asyncio
import logging
from typing import IO
from mitmproxy import log

class TermLog:
    _teardown_task: asyncio.Task | None = ...
    def __init__(self, out: IO[str] | None = ...) -> None:
        ...
    
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def uninstall(self) -> None:
        ...
    


class TermLogHandler(log.MitmLogHandler):
    def __init__(self, out: IO[str] | None = ...) -> None:
        ...
    
    def emit(self, record: logging.LogRecord) -> None:
        ...
    


