"""
This type stub file was generated by pyright.
"""

from mitmproxy.http import HTTPFlow

ALT_SVC = ...
HOST_PATTERN = ...
def update_alt_svc_header(header: str, port: int) -> str:
    ...

class UpdateAltSvc:
    def load(self, loader): # -> None:
        ...
    
    def responseheaders(self, flow: HTTPFlow): # -> None:
        ...
    


