"""
This type stub file was generated by pyright.
"""

from mitmproxy import http

def parse_upstream_auth(auth: str) -> bytes:
    ...

class UpstreamAuth:
    """
    This addon handles authentication to systems upstream from us for the
    upstream proxy and reverse proxy mode. There are 3 cases:

    - Upstream proxy CONNECT requests should have authentication added, and
      subsequent already connected requests should not.
    - Upstream proxy regular requests
    - Reverse proxy regular requests (CONNECT is invalid in this mode)
    """
    auth: bytes | None = ...
    def load(self, loader): # -> None:
        ...
    
    def configure(self, updated): # -> None:
        ...
    
    def http_connect_upstream(self, f: http.HTTPFlow): # -> None:
        ...
    
    def requestheaders(self, f: http.HTTPFlow): # -> None:
        ...
    


