"""
This type stub file was generated by pyright.
"""

from msilib import Control, Dialog

"""Extend msilib Dialog."""
class PyDialog(Dialog):
    """Dialog class with a fixed layout: controls at the top, then a ruler,
    then a list of buttons: back, next, cancel. Optionally a bitmap at the
    left.
    """
    def __init__(self, db, name, x, y, w, h, attr, title, first, default, cancel, bitmap=...) -> None:
        ...
    
    def title(self, title) -> None:
        """Set the title text of the dialog at the top."""
        ...
    
    def backbutton(self, title, tabnext, name=..., active=...) -> Control:
        """Add a back button with a given title, the tab-next button,
        its name in the Control table, possibly initially disabled.

        Return the button, so that events can be associated
        """
        ...
    
    def cancelbutton(self, title, tabnext, name=..., active=...) -> Control:
        """Add a cancel button with a given title, the tab-next button,
        its name in the Control table, possibly initially disabled.

        Return the button, so that events can be associated
        """
        ...
    
    def nextbutton(self, title, tabnext, name=..., active=...) -> Control:
        """Add a Next button with a given title, the tab-next button,
        its name in the Control table, possibly initially disabled.

        Return the button, so that events can be associated
        """
        ...
    
    def xbutton(self, name, title, tabnext, xpos) -> Control:
        """Add a button with a given title, the tab-next button,
        its name in the Control table, giving its x position; the
        y-position is aligned with the other buttons.

        Return the button, so that events can be associated
        """
        ...
    


