"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from setuptools import Command

"""Implements the 'bdist_rpm' command (create RPM binary distributions).

Borrowed from distutils.command.bdist_rpm of Python 3.10 and merged with
bdist_rpm subclass of cx_Freeze 6.10.

https://rpm.org/documentation.html
https://rpm-packaging-guide.github.io/

"""
__all__ = ["bdist_rpm"]
class bdist_rpm(Command):
    """Create an RPM distribution."""
    description = ...
    user_options: ClassVar[list[tuple[str, str | None, str]]] = ...
    boolean_options: ClassVar[list[str]] = ...
    negative_opt: ClassVar[dict[str, str]] = ...
    def initialize_options(self) -> None:
        ...
    
    def finalize_options(self) -> None:
        ...
    
    def finalize_package_data(self) -> None:
        ...
    
    def run(self) -> None:
        ...
    


def write_file(filename, contents) -> None:
    """Create a file with the specified name and write 'contents'
    (a sequence of strings without line terminators) to it.
    """
    ...

