"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from setuptools import Command

"""Implements the 'bdist_dmg' command (create macOS dmg and/or app bundle)."""
__all__ = ["bdist_dmg"]
class bdist_dmg(Command):
    """Create a Mac DMG disk image containing the Mac application bundle."""
    description = ...
    user_options: ClassVar[list[tuple[str, str | None, str]]] = ...
    def initialize_options(self) -> None:
        ...
    
    def finalize_options(self) -> None:
        ...
    
    def finalize_dmgbuild_options(self) -> None:
        ...
    
    def build_dmg(self) -> None:
        ...
    
    def run(self) -> None:
        ...
    


