"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from setuptools import Command

"""Implements the 'bdist_appimage' command (create Linux AppImage format).

https://appimage.org/
https://docs.appimage.org/
https://docs.appimage.org/packaging-guide/manual.html#ref-manual
"""
__all__ = ["bdist_appimage"]
ARCH = ...
APPIMAGEKIT_URL = ...
APPIMAGEKIT_PATH = ...
APPIMAGEKIT_TOOL = ...
class bdist_appimage(Command):
    """Create a Linux AppImage."""
    description = ...
    user_options: ClassVar[list[tuple[str, str | None, str]]] = ...
    boolean_options: ClassVar[list[str]] = ...
    def initialize_options(self) -> None:
        ...
    
    def finalize_options(self) -> None:
        ...
    
    def run(self) -> None:
        ...
    
    def save_as_file(self, data, outfile, mode=...) -> tuple[str, int]:
        """Save an input data to a file respecting verbose, dry-run and force
        flags.
        """
        ...
    
    def warn_delayed(self, msg) -> None:
        ...
    
    def warnings(self) -> None:
        ...
    


