"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from setuptools import Command

"""Implements the 'bdist_mac' commands (create macOS
app blundle).
"""
__all__ = ["bdist_mac"]
class bdist_mac(Command):
    """Create a Mac application bundle."""
    description = ...
    plist_items: list[tuple[str, str]]
    include_frameworks: list[str]
    include_resources: list[str]
    user_options: ClassVar[list[tuple[str, str | None, str]]] = ...
    def initialize_options(self) -> None:
        ...
    
    def finalize_options(self) -> None:
        ...
    
    def create_plist(self) -> None:
        """Create the Contents/Info.plist file."""
        ...
    
    def set_absolute_reference_paths(self, path=...) -> None:
        """For all files in Contents/MacOS, set their linked library paths to
        be absolute paths using the given path instead of @executable_path.
        """
        ...
    
    def find_qt_menu_nib(self) -> str | None:
        """Returns a location of a qt_menu.nib folder, or None if this is not
        a Qt application.
        """
        ...
    
    def prepare_qt_app(self) -> None:
        """Add resource files for a Qt application. Should do nothing if the
        application does not use QtCore.
        """
        ...
    
    def run(self) -> None:
        ...
    


