"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from setuptools import Command

"""Implements the 'bdist_deb' command (create DEB binary distributions).

This is a simple wrapper around 'alien' that converts a rpm to deb.
"""
__all__ = ["bdist_deb"]
class bdist_deb(Command):
    """Create an DEB distribution."""
    description = ...
    user_options: ClassVar[list[tuple[str, str | None, str]]] = ...
    def initialize_options(self) -> None:
        ...
    
    def finalize_options(self) -> None:
        ...
    
    def run(self) -> None:
        ...
    


