"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from setuptools import Command

"""Implements the 'build_exe' command."""
__all__ = ["build_exe"]
class build_exe(Command):
    """Build executables from Python scripts."""
    description = ...
    user_options: ClassVar[list[tuple[str, str | None, str]]] = ...
    boolean_options: ClassVar[list[str]] = ...
    def add_to_path(self, name) -> None:
        ...
    
    def build_extension(self, name, module_name=...) -> str | None:
        ...
    
    def initialize_options(self) -> None:
        ...
    
    def finalize_options(self) -> None:
        ...
    
    def run(self) -> None:
        ...
    
    def set_source_location(self, name, *pathParts) -> None:
        ...
    
    def has_executables(self) -> bool:
        ...
    


