"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from setuptools import Command

"""Implements the 'install_exe' command."""
__all__ = ["install_exe"]
class install_exe(Command):
    """Install executables built from Python scripts."""
    command_name = ...
    description = ...
    user_options: ClassVar[list[tuple[str, str | None, str]]] = ...
    def initialize_options(self) -> None:
        ...
    
    def finalize_options(self) -> None:
        ...
    
    def run(self) -> None:
        ...
    
    def get_inputs(self) -> list[str]:
        ...
    
    def get_outputs(self) -> list[str]:
        ...
    


