"""
This type stub file was generated by pyright.
"""

Metadata = list[tuple[str, str]]
def parse_png(data: bytes) -> Metadata:
    ...

def parse_gif(data: bytes) -> Metadata:
    ...

def parse_jpeg(data: bytes) -> Metadata:
    ...

def parse_ico(data: bytes) -> Metadata:
    ...

