"""
This type stub file was generated by pyright.
"""

from mitmproxy.contentviews import base

def test_ico(h, f): # -> Literal['ico'] | None:
    ...

class ViewImage(base.View):
    name = ...
    def __call__(self, data, **metadata): # -> tuple[str, Iterator[TViewLine]]:
        ...
    
    def render_priority(self, data: bytes, *, content_type: str | None = ..., **metadata) -> float:
        ...
    


