"""
This type stub file was generated by pyright.
"""

import typing
import mitmproxy.log
import mitmproxy.master
import mitmproxy.options

if typing.TYPE_CHECKING:
    ...
master: mitmproxy.master.Master
options: mitmproxy.options.Options
log: mitmproxy.log.Log
