"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Iterator
from typing import Any
from mitmproxy import flow, hooks

TEventGenerator = Iterator[hooks.Hook]
_iterate_map: dict[type[flow.Flow], Callable[[Any], TEventGenerator]] = ...
def iterate(f: flow.Flow) -> TEventGenerator:
    ...

