"""
This type stub file was generated by pyright.
"""

import asyncio
from .addons import termlog
from mitmproxy import command
from mitmproxy import options
from mitmproxy import addonmanager

logger = ...

class Master:
    """
    The master handles mitmproxy's main event loop.
    """

    options: options.Options
    commands: command.CommandManager
    event_loop: asyncio.AbstractEventLoop
    addons: addonmanager.AddonManager
    _termlog_addon: termlog.TermLog | None = ...
    def __init__(
        self,
        opts: options.Options,
        event_loop: asyncio.AbstractEventLoop | None = ...,
        with_termlog: bool = ...,
    ) -> None: ...
    async def run(self) -> None: ...
    def shutdown(self):  # -> None:
        """
        Shut down the proxy. This method is thread-safe.
        """
        ...

    async def running(self) -> None: ...
    async def done(self) -> None: ...
    async def load_flow(self, f):  # -> None:
        """
        Loads a flow
        """
        ...
