"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Any, TYPE_CHECKING, Union
from mitmproxy import flow
from mitmproxy.command import CommandManager

if TYPE_CHECKING:
    ...
class Path(str):
    ...


class Cmd(str):
    ...


class CmdArgs(str):
    ...


class Unknown(str):
    ...


class Space(str):
    ...


class CutSpec(Sequence[str]):
    ...


class Data(Sequence[Sequence[Union[str, bytes]]]):
    ...


class Marker(str):
    ...


class Choice:
    def __init__(self, options_command) -> None:
        ...
    
    def __instancecheck__(self, instance): # -> Literal[False]:
        ...
    


class _BaseType:
    typ: type = ...
    display: str = ...
    def completion(self, manager: CommandManager, t: Any, s: str) -> Sequence[str]:
        """
        Returns a list of completion strings for a given prefix. The strings
        returned don't necessarily need to be suffixes of the prefix, since
        completers will do prefix filtering themselves..
        """
        ...
    
    def parse(self, manager: CommandManager, typ: Any, s: str) -> Any:
        """
        Parse a string, given the specific type instance (to allow rich type annotations like Choice) and a string.

        Raises ValueError if the value is invalid.
        """
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        """
        Check if data is valid for this type.
        """
        ...
    


class _BoolType(_BaseType):
    typ = bool
    display = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> bool:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _StrType(_BaseType):
    typ = str
    display = ...
    escape_sequences = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> str:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _BytesType(_BaseType):
    typ = bytes
    display = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> bytes:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _UnknownType(_BaseType):
    typ = Unknown
    display = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> str:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _IntType(_BaseType):
    typ = int
    display = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> int:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _PathType(_BaseType):
    typ = Path
    display = ...
    def completion(self, manager: CommandManager, t: type, start: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> str:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _CmdType(_BaseType):
    typ = Cmd
    display = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> str:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _ArgType(_BaseType):
    typ = CmdArgs
    display = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> str:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _StrSeqType(_BaseType):
    typ = Sequence[str]
    display = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _CutSpecType(_BaseType):
    typ = CutSpec
    display = ...
    valid_prefixes = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> CutSpec:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _BaseFlowType(_BaseType):
    viewmarkers = ...
    valid_prefixes = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    


class _FlowType(_BaseFlowType):
    typ = flow.Flow
    display = ...
    def parse(self, manager: CommandManager, t: type, s: str) -> flow.Flow:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _FlowsType(_BaseFlowType):
    typ = Sequence[flow.Flow]
    display = ...
    def parse(self, manager: CommandManager, t: type, s: str) -> Sequence[flow.Flow]:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _DataType(_BaseType):
    typ = Data
    display = ...
    def completion(self, manager: CommandManager, t: type, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: type, s: str) -> Any:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


class _ChoiceType(_BaseType):
    typ = Choice
    display = ...
    def completion(self, manager: CommandManager, t: Choice, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: Choice, s: str) -> str:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: Any) -> bool:
        ...
    


ALL_MARKERS = ...
class _MarkerType(_BaseType):
    typ = Marker
    display = ...
    def completion(self, manager: CommandManager, t: Choice, s: str) -> Sequence[str]:
        ...
    
    def parse(self, manager: CommandManager, t: Choice, s: str) -> str:
        ...
    
    def is_valid(self, manager: CommandManager, typ: Any, val: str) -> bool:
        ...
    


class TypeManager:
    def __init__(self, *types) -> None:
        ...
    
    def get(self, t: type | None, default=...) -> _BaseType | None:
        ...
    


CommandTypes = ...
