"""
This type stub file was generated by pyright.
"""

def parse_content_type(c: str) -> tuple[str, str, dict[str, str]] | None:
    """
    A simple parser for content-type values. Returns a (type, subtype,
    parameters) tuple, where type and subtype are strings, and parameters
    is a dict. If the string could not be parsed, return None.

    E.g. the following string:

        text/html; charset=UTF-8

    Returns:

        ("text", "html", {"charset": "UTF-8"})
    """
    ...

def assemble_content_type(type, subtype, parameters): # -> str:
    ...

def infer_content_encoding(content_type: str, content: bytes = ...) -> str:
    """
    Infer the encoding of content from the content-type header.
    """
    ...

