"""
This type stub file was generated by pyright.
"""

def encode_multipart(content_type: str, parts: list[tuple[bytes, bytes]]) -> bytes:
    ...

def decode_multipart(content_type: str | None, content: bytes) -> list[tuple[bytes, bytes]]:
    """
    Takes a multipart boundary encoded string and returns list of (key, value) tuples.
    """
    ...

def encode(ct, parts): # -> bytes:
    ...

def decode(ct, content): # -> bytes:
    ...

