"""
This type stub file was generated by pyright.
"""

import typing
from mitmproxy.http import Message

logger = ...
_valid_header_name = ...
_valid_content_length = ...
_valid_content_length_str = ...
TransferEncoding = typing.Literal["chunked", "compress,chunked", "deflate,chunked", "gzip,chunked", "compress", "deflate", "gzip", "identity",]
_HTTP_1_1_TRANSFER_ENCODINGS = ...
def parse_content_length(value: str | bytes) -> int:
    """Parse a content-length header value, or raise a ValueError if it is invalid."""
    ...

def parse_transfer_encoding(value: str | bytes) -> TransferEncoding:
    """Parse a transfer-encoding header value, or raise a ValueError if it is invalid or unknown."""
    ...

def validate_headers(message: Message) -> None:
    """
    Validate HTTP message headers to avoid request smuggling attacks.

    Raises a ValueError if they are malformed.
    """
    ...

