"""
This type stub file was generated by pyright.
"""

from mitmproxy import http

"""Reads HAR files into flow objects"""
logger = ...
def fix_headers(request_headers: list[dict[str, str]] | list[tuple[str, str]]) -> http.Headers:
    """Converts provided headers into (b"header-name", b"header-value") tuples"""
    ...

def request_to_flow(request_json: dict) -> http.HTTPFlow:
    """
    Creates a HTTPFlow object from a given entry in HAR file
    """
    ...

