"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from mitmproxy.connection import Connection
from mitmproxy.proxy import commands, events, layer
from mitmproxy.proxy.context import Context

StreamId = int
@dataclass
class HttpEvent(events.Event):
    stream_id: StreamId
    ...


class HttpConnection(layer.Layer):
    conn: Connection
    def __init__(self, context: Context, conn: Connection) -> None:
        ...
    


class HttpCommand(commands.Command):
    ...


class ReceiveHttp(HttpCommand):
    event: HttpEvent
    def __init__(self, event: HttpEvent) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


def format_error(status_code: int, message: str) -> bytes:
    ...

