"""
This type stub file was generated by pyright.
"""

from h11._receivebuffer import ReceiveBuffer
from mitmproxy import connection
from mitmproxy.proxy import context, layer, tunnel

class HttpUpstreamProxy(tunnel.TunnelLayer):
    buf: ReceiveBuffer
    send_connect: bool
    conn: connection.Server
    tunnel_connection: connection.Server
    def __init__(self, ctx: context.Context, tunnel_conn: connection.Server, send_connect: bool) -> None:
        ...
    
    @classmethod
    def make(cls, ctx: context.Context, send_connect: bool) -> tunnel.LayerStack:
        ...
    
    def start_handshake(self) -> layer.CommandGenerator[None]:
        ...
    
    def receive_handshake_data(self, data: bytes) -> layer.CommandGenerator[tuple[bool, str | None]]:
        ...
    


