"""
This type stub file was generated by pyright.
"""

import re
import socket
import sys
from collections.abc import Callable
from . import linux, osx

def init_transparent_mode() -> None:
    """
    Initialize transparent mode.
    """
    ...

original_addr: Callable[[socket.socket], tuple[str, int]] | None
if re.match(r"linux(?:2)?", sys.platform):
    original_addr = ...
else:
    original_addr = ...
__all__ = ["original_addr", "init_transparent_mode"]
