"""
This type stub file was generated by pyright.
"""

from win32.win32pipe import *
import _win32typing

def CreateNamedPipe(
    pipeName: str,
    openMode: int,
    pipeMode: int,
    nMaxInstances: int,
    nOutBufferSize: int,
    nInBufferSize: int,
    nDefaultTimeOut: int,
    sa: _win32typing.PySECURITY_ATTRIBUTES | None,
    /,
) -> int: ...
def ConnectNamedPipe(
    hPipe: int, overlapped: _win32typing.PyOVERLAPPED | None = ..., /
) -> int: ...
