"""
This type stub file was generated by pyright.
"""

"""Recognize image file formats based on their first few bytes."""
__all__ = ["what"]
def what(file, h=...): # -> None:
    """Return the type of image contained in a file or byte stream."""
    ...

tests = ...
def test_jpeg(h, f): # -> Literal['jpeg'] | None:
    """Test for JPEG data with JFIF or Exif markers; and raw JPEG."""
    ...

def test_png(h, f): # -> Literal['png'] | None:
    """Verify if the image is a PNG."""
    ...

def test_gif(h, f): # -> Literal['gif'] | None:
    """Verify if the image is a GIF ('87 or '89 variants)."""
    ...

def test_tiff(h, f): # -> Literal['tiff'] | None:
    """Verify if the image is a TIFF (can be in Motorola or Intel byte order)."""
    ...

def test_rgb(h, f): # -> Literal['rgb'] | None:
    """test for the SGI image library."""
    ...

def test_pbm(h, f): # -> Literal['pbm'] | None:
    """Verify if the image is a PBM (portable bitmap)."""
    ...

def test_pgm(h, f): # -> Literal['pgm'] | None:
    """Verify if the image is a PGM (portable graymap)."""
    ...

def test_ppm(h, f): # -> Literal['ppm'] | None:
    """Verify if the image is a PPM (portable pixmap)."""
    ...

def test_rast(h, f): # -> Literal['rast'] | None:
    """test for the Sun raster file."""
    ...

def test_xbm(h, f): # -> Literal['xbm'] | None:
    """Verify if the image is a X bitmap (X10 or X11)."""
    ...

def test_bmp(h, f): # -> Literal['bmp'] | None:
    """Verify if the image is a BMP file."""
    ...

def test_webp(h, f): # -> Literal['webp'] | None:
    """Verify if the image is a WebP."""
    ...

def test_exr(h, f): # -> Literal['exr'] | None:
    """verify is the image ia a OpenEXR fileOpenEXR."""
    ...

