"""
This type stub file was generated by pyright.
"""

class Chunk:
    header_magic = ...
    def __init__(self) -> None:
        ...
    
    @property
    def data(self): # -> bytes:
        ...
    
    @data.setter
    def data(self, value: bytes): # -> None:
        ...
    
    @property
    def guid_str(self): # -> str:
        ...
    
    @property
    def guid_num(self): # -> Any | int:
        ...
    
    @property
    def compressed(self): # -> int:
        ...
    
    @classmethod
    def read_buffer(cls, data): # -> Self@Chunk:
        ...
    
    @classmethod
    def read(cls, bio): # -> Self@Chunk:
        ...
    
    def write(self, fp=..., compress=...): # -> int | bytes:
        ...
    


