"""
This type stub file was generated by pyright.
"""

from .baseclient import BaseClient
from .client import AioClient, Client
from .exceptions import *
from .presence import *

"""
Python RPC Client for Discord
-----------------------------
By: qwertyquerty and LewdNeko
"""
__title__ = ...
__author__ = ...
__copyright__ = ...
__license__ = ...
__version__ = ...
