"""
This type stub file was generated by pyright.
"""

class PyPresenceException(Exception):
    def __init__(self, message: str = ...) -> None:
        ...
    


class DiscordNotFound(PyPresenceException):
    def __init__(self) -> None:
        ...
    


class InvalidPipe(PyPresenceException):
    def __init__(self) -> None:
        ...
    


class InvalidArgument(PyPresenceException):
    def __init__(self, expected, received, description: str = ...) -> None:
        ...
    


class ServerError(PyPresenceException):
    def __init__(self, message: str) -> None:
        ...
    


class DiscordError(PyPresenceException):
    def __init__(self, code: int, message: str, override=...) -> None:
        ...
    


class InvalidID(DiscordError):
    def __init__(self) -> None:
        ...
    


class ArgumentError(PyPresenceException):
    def __init__(self) -> None:
        ...
    


class EventNotFound(PyPresenceException):
    def __init__(self, event) -> None:
        ...
    


class PipeClosed(PyPresenceException):
    def __init__(self) -> None:
        ...
    


class ResponseTimeout(PyPresenceException):
    def __init__(self) -> None:
        ...
    


class ConnectionTimeout(PyPresenceException):
    def __init__(self) -> None:
        ...
    


