"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from mitmproxy.tls import ClientHello

"""
This module contains a very terrible QUIC client hello parser.

Nothing is more permanent than a temporary solution!
"""
@dataclass
class QuicClientHello(Exception):
    """Helper error only used in `quic_parse_client_hello_from_datagrams`."""
    data: bytes
    ...


def quic_parse_client_hello_from_datagrams(datagrams: list[bytes]) -> Optional[ClientHello]:
    """
    Check if the supplied bytes contain a full ClientHello message,
    and if so, parse it.

    Args:
        - msgs: list of ClientHello fragments received from client

    Returns:
        - A ClientHello object on success
        - None, if the QUIC record is incomplete

    Raises:
        - A ValueError, if the passed ClientHello is invalid
    """
    ...

