"""
This type stub file was generated by pyright.
"""

from mitmproxy import connection
from mitmproxy.proxy import commands

class QuicStreamCommand(commands.ConnectionCommand):
    """Base class for all QUIC stream commands."""
    stream_id: int
    def __init__(self, connection: connection.Connection, stream_id: int) -> None:
        ...
    


class SendQuicStreamData(QuicStreamCommand):
    """Command that sends data on a stream."""
    data: bytes
    end_stream: bool
    def __init__(self, connection: connection.Connection, stream_id: int, data: bytes, end_stream: bool = ...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class ResetQuicStream(QuicStreamCommand):
    """Abruptly terminate the sending part of a stream."""
    error_code: int
    def __init__(self, connection: connection.Connection, stream_id: int, error_code: int) -> None:
        ...
    


class StopSendingQuicStream(QuicStreamCommand):
    """Request termination of the receiving part of a stream."""
    error_code: int
    def __init__(self, connection: connection.Connection, stream_id: int, error_code: int) -> None:
        ...
    


class CloseQuicConnection(commands.CloseConnection):
    """Close a QUIC connection."""
    error_code: int
    frame_type: int | None
    reason_phrase: str
    def __init__(self, conn: connection.Connection, error_code: int, frame_type: int | None, reason_phrase: str) -> None:
        ...
    


