"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from ssl import VerifyMode
from aioquic.tls import CipherSuite
from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import dsa, ec, rsa
from mitmproxy.proxy import commands
from mitmproxy.tls import TlsData

@dataclass
class QuicTlsSettings:
    """
    Settings necessary to establish QUIC's TLS context.
    """
    alpn_protocols: list[str] | None = ...
    certificate: x509.Certificate | None = ...
    certificate_chain: list[x509.Certificate] = ...
    certificate_private_key: (dsa.DSAPrivateKey | ec.EllipticCurvePrivateKey | rsa.RSAPrivateKey | None) = ...
    cipher_suites: list[CipherSuite] | None = ...
    ca_path: str | None = ...
    ca_file: str | None = ...
    verify_mode: VerifyMode | None = ...


@dataclass
class QuicTlsData(TlsData):
    """
    Event data for `quic_start_client` and `quic_start_server` event hooks.
    """
    settings: QuicTlsSettings | None = ...


@dataclass
class QuicStartClientHook(commands.StartHook):
    """
    TLS negotiation between mitmproxy and a client over QUIC is about to start.

    An addon is expected to initialize data.settings.
    (by default, this is done by `mitmproxy.addons.tlsconfig`)
    """
    data: QuicTlsData
    ...


@dataclass
class QuicStartServerHook(commands.StartHook):
    """
    TLS negotiation between mitmproxy and a server over QUIC is about to start.

    An addon is expected to initialize data.settings.
    (by default, this is done by `mitmproxy.addons.tlsconfig`)
    """
    data: QuicTlsData
    ...


