"""
This type stub file was generated by pyright.
"""

import sys
import setuptools
from typing import Any
from __future__ import annotations
from cx_Freeze.command.build_exe import build_exe
from cx_Freeze.command.install import Install as install
from cx_Freeze.command.install_exe import install_exe
from cx_Freeze.executable import Executable, validate_executables
from cx_Freeze.finder import Module, ModuleFinder
from cx_Freeze.freezer import ConstantsModule, Freezer
from cx_Freeze.command.bdist_msi import bdist_msi

"""Create standalone executables from Python scripts, with the same performance
and is cross-platform.
"""
__all__ = ["ConstantsModule", "Executable", "Freezer", "Module", "ModuleFinder", "__version__", "build_exe", "install", "install_exe", "setup"]
if sys.platform == "win32":
    ...
else:
    ...
__version__ = ...
def setup(**attrs: Any) -> setuptools.Distribution:
    ...

def plugin_install(dist: setuptools.Distribution) -> None:
    """Use a setuptools extension to customize Distribution options."""
    ...

