"""
This type stub file was generated by pyright.
"""

from typing import TypeAlias

"""The internal _typing module."""
DeferredList: TypeAlias = ...
IncludesList: TypeAlias = ...
InternalIncludesList: TypeAlias = ...
__all__ = ["DeferredList", "IncludesList", "InternalIncludesList", "TypeAlias"]
