"""
This type stub file was generated by pyright.
"""

import argparse

"""cxfreeze command line tool."""
__all__ = ["main"]
DESCRIPTION = ...
VERSION = ...
EPILOG = ...
def prepare_parser() -> argparse.ArgumentParser:
    """Helper function to parse the arguments."""
    ...

def main() -> None:
    """Entry point for cxfreeze command line tool."""
    ...

