"""
This type stub file was generated by pyright.
"""

from typing import ClassVar

"""cxfreeze-quickstart command line tool."""
class SetupWriter:
    """SetupWriter class."""
    bases: ClassVar[dict[str, str]] = ...
    @property
    def base(self) -> str:
        ...
    
    @property
    def default_executable_name(self) -> str:
        ...
    
    def __init__(self) -> None:
        ...
    
    def get_boolean_value(self, label, default=...) -> bool:
        ...
    
    def get_value(self, label, default=..., separator=...) -> str:
        ...
    
    def populate_from_command_line(self) -> None:
        ...
    
    def write(self) -> None:
        ...
    


def main() -> None:
    """Entry point for cxfreeze-quickstart command line tool."""
    ...

